# Generated by Django 4.2 on 2024-09-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=18, verbose_name='手机号码')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('info', models.CharField(max_length=200, verbose_name='详细地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='所属用户')),
            ],
        ),
    ]
